name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
      POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
      
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: aariz26/prod-pdf-reader:latest  # Replace with your Docker Hub username and repository
        build-args: |
          POSTGRES_PRISMA_URL=${{ secrets.POSTGRES_PRISMA_URL }}
          POSTGRES_URL_NON_POOLING=${{ secrets.POSTGRES_URL_NON_POOLING }}

    - name: Verify Pushed Image
      run: docker pull aariz26/prod-pdf-reader:latest  # Replace with your Docker Hub username and repository

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull aariz26/prod-pdf-reader:latest
          sudo docker stop prod-pdf-reader || true
          sudo docker rm prod-pdf-reader || true
          sudo docker run -d --name prod-pdf-reader -p 3005:3000 aariz26/prod-pdf-reader:latest